Create table alert (alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1),
                    name varchar(250),
                    description varchar(500),
                    query  varchar(1500),
                    customer_id NUMBER,
                    PRIMARY KEY (Alert_ID));
                    
                    
Create table customer (customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 10000 INCREMENT BY 1),
                    name varchar(250),
                    PRIMARY KEY (customer_id)
                    );
                    
Alter Table alert add constraint fk_alert_customer Foreign Key(customer_id) References customer (customer_id);

CREATE SEQUENCE alert.hibernate_sequence INCREMENT BY 1 START WITH 100;

SELECT CUSTOMER_ID ,NAME  from Customer;
SELECT ALERT_ID ,NAME ,DESCRIPTION ,QUERY ,CUSTOMER_ID  from Alert;